"""
features/configs.py — Feature category definitions and LLM settings for the
                       third graph layer (Feature Extraction)

Why is this file separate from vocabulary_categorizer.py?
    These settings (category names, descriptions, LLM model) are needed in
    several places: the one-time vocabulary categorization step, and later
    in extractor.py (per-ruling feature extraction). Same pattern as
    laws/configs.py, used by both parser.py and main_cases.py.

Why is "Referenced Articles" not defined here?
    Per an earlier decision, that feature is already extracted with regex
    in cases/parser.py (cited_articles / text_cited_articles) and should
    not be regenerated by an LLM. This file only covers categories that
    genuinely need one.

Why is "Legal Facts" a separate category with no closed vocabulary?
    Facts (e.g. "payment was not made") are unboundedly varied and can't be
    enumerated in advance; they must be extracted freely from the text
    (with an evidence span, per the original design). That's why it's not
    in VOCAB_CATEGORIES — it's not meant to be classified against an
    existing vocabulary.

    Note: linking a Fact (when relevant) to a structured node (Role/
    Action/Object) was proposed and deliberately rejected — a Fact must
    always stay as free, complete text, with no link or dependency on the
    closed vocabulary, so case information isn't pruned.

Why is normalization/alias resolution done in the same categorization
pass, not a separate second pass?
    A second pass would mean sending the whole vocabulary to the LLM again
    — double the cost for something the LLM can do at the same time as
    categorization. So in vocabulary_categorizer.py, alongside "category",
    a "root" (canonical form) field is also requested: e.g. "عقد بیع" and
    "قرارداد بیع" both return category=concept and root="بیع".

Why was "principle" dropped?
    In practice (per vocabulary_categorizer.py's report), out of 377 raw
    terms only 6 were genuinely meaningful legal principles (98% noise —
    connectives and adverbs like "با توجه به", "مستنداً", "هرچند"). Those
    6 remaining terms were manually moved into concept aliases; this
    category is no longer extracted by the pipeline.

LLM provider:
    A single provider — OpenRouter — is used for the whole pipeline, with
    the model set in OPENROUTER_MODEL below. There is no fallback chain;
    if the call fails, get_llm_client()'s client raises and the caller's
    own retry loop (see extractor.py / vocabulary_categorizer.py) handles it.
"""

from dataclasses import dataclass
import os
from dotenv import load_dotenv

load_dotenv()


@dataclass(frozen=True)
class FeatureCategoryDef:
    key: str                # internal key, e.g. "concept"
    label_fa: str            # Persian label, for display/prompting
    description: str         # description for the LLM (the agreed-upon definition)
    examples: list[str]
    node_label: str          # Neo4j node label, e.g. "LegalConcept"
    relation_type: str       # relation type from Ruling, e.g. "HAS_CONCEPT"
    from_closed_vocabulary: bool   # should this category be chosen from the closed vocabulary?


# Categories that must be categorized from data/legal-vocabulary/legal_vocabulary.json
# (i.e. Step 1 — vocabulary_categorizer.py runs against these)
VOCAB_CATEGORIES: dict[str, FeatureCategoryDef] = {
    "concept": FeatureCategoryDef(
        key="concept",
        label_fa="مفهوم حقوقی (Legal Concept)",
        description=(
            "یک مفهوم یا نهاد حقوقی انتزاعی که در حقوق مدنی/کیفری/تجاری "
            "تعریف‌شده است — نه یک شیء فیزیکی و نه یک نقش انسانی. شامل "
            "اصول کلی حقوقی هم می‌شود (مثل اصل برائت، اصل لزوم قرارداد). "
            "مثال‌ها: اهلیت، فسخ، خیار، عدم ایفای تعهد، اکراه، غرر، "
            "اصل برائت، اصل لزوم قرارداد."
        ),
        examples=["اهلیت", "فسخ", "خیار", "غرر", "اکراه", "اصل برائت", "اصل لزوم قرارداد"],
        node_label="LegalConcept",
        relation_type="HAS_CONCEPT",
        from_closed_vocabulary=True,
    ),
    "action": FeatureCategoryDef(
        key="action",
        label_fa="رفتار حقوقی (Legal Action)",
        description=(
            "یک فعل/رفتار حقوقی که یکی از طرفین دعوا انجام داده یا نداده "
            "است — معمولاً به‌صورت فعل یا مصدر. "
            "مثال‌ها: پرداخت کرد، پرداخت نکرد، فسخ کرد، مطالبه کرد، "
            "ابطال کرد، اقامه دعوا کرد، اعتراض کرد."
        ),
        examples=["پرداخت", "فسخ کرد", "مطالبه", "ابطال", "اقامه دعوا", "اعتراض"],
        node_label="LegalAction",
        relation_type="HAS_ACTION",
        from_closed_vocabulary=True,
    ),
    "role": FeatureCategoryDef(
        key="role",
        label_fa="نقش حقوقی (Legal Role)",
        description=(
            "عنوانی که یکی از طرفین دعوا یا یک شخص ثالث در پرونده بر عهده "
            "دارد. مثال‌ها: خواهان، خوانده، مستأجر، موجر، فروشنده، خریدار."
        ),
        examples=["خواهان", "خوانده", "مستأجر", "موجر", "فروشنده", "خریدار"],
        node_label="LegalRole",
        relation_type="HAS_ROLE",
        from_closed_vocabulary=True,
    ),
    "object": FeatureCategoryDef(
        key="object",
        label_fa="موضوع/شیء حقوقی (Legal Object)",
        description=(
            "یک شیء، سند، یا دارایی که موضوع دعوا یا معامله است. "
            "مثال‌ها: ملک، چک، قرارداد، سند، وجه نقد، وصیت‌نامه."
        ),
        examples=["ملک", "چک", "قرارداد", "سند", "وجه نقد", "وصیت‌نامه"],
        node_label="LegalObject",
        relation_type="HAS_OBJECT",
        from_closed_vocabulary=True,
    ),
}

# Legal Facts are not categorized from the vocabulary (extracted freely from
# the text), but the definition is kept here for consistent use in both
# extractor.py and documentation.
FACT_CATEGORY = FeatureCategoryDef(
    key="fact",
    label_fa="واقعه‌ی حقوقی (Legal Fact)",
    description=(
        "یک واقعه یا وضعیتِ رخ‌داده در پرونده که به‌صورت آزاد از متن "
        "استخراج می‌شود (نه از واژه‌نامه). مثال‌ها: پرداخت انجام نشده، "
        "قرارداد امضا شده، تحویل کالا انجام نشده، سند جعلی ارائه شده."
    ),
    examples=[
        "پرداخت انجام نشده",
        "قرارداد امضا شده",
        "تحویل کالا انجام نشده",
        "سند جعلی ارائه شده",
    ],
    node_label="LegalFact",
    relation_type="HAS_FACT",
    from_closed_vocabulary=False,
)

# Label meaning "this term is not a useful legal feature at all" — needed
# because legal_vocabulary.json is a general legal dictionary (includes
# purely linguistic entries like "ابعد: farther"), not just technical terms.
# Without this option, the LLM would be forced to fit every term into one
# of the categories, hurting accuracy.
SKIP_LABEL = "skip"

ALL_VOCAB_LABELS = list(VOCAB_CATEGORIES.keys()) + [SKIP_LABEL]


# ============================================================
# --- LLM settings: single provider (OpenRouter) ---
# ============================================================

LLM_TEMPERATURE = 0.1
MAX_OUTPUT_TOKENS = 6000

# Model actually used for this project's runs.
OPENROUTER_MODEL = "models/gemini-2.6-flash"

# Kept for logging/back-compat with code that imports LLM_MODEL directly.
LLM_MODEL = OPENROUTER_MODEL


class _ChatClient:
    """
    Presents the same interface extractor.py / vocabulary_categorizer.py
    expect from an OpenAI-compatible client
    (`_client.chat.completions.create(model=..., messages=..., temperature=...)`,
    reading `response.choices[0].message.content`), backed by a single
    OpenRouter call. No fallback to other providers — if the request
    fails, it raises and the caller's own retry loop handles it.
    """

    class _Msg:
        def __init__(self, content):
            self.content = content

    class _Choice:
        def __init__(self, content):
            self.message = _ChatClient._Msg(content)

    class _Response:
        def __init__(self, content):
            self.choices = [_ChatClient._Choice(content)]

    class _Completions:
        def __init__(self, call_fn):
            self._call_fn = call_fn  # (prompt, temperature) -> str

        def create(self, model: str, messages: list[dict], temperature: float = 0.1, **_):
            prompt = messages[0]["content"]
            text = self._call_fn(prompt, temperature)
            return _ChatClient._Response(text)

    def __init__(self, call_fn):
        self.chat = self
        self.completions = self._Completions(call_fn)


def _make_openrouter_call():
    """
    OpenRouter call (OpenAI-compatible proxy). Requires OPENROUTER_API_KEY
    in .env (get one at https://openrouter.ai/keys).
    """
    from openai import OpenAI

    client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=os.getenv("OPENROUTER_API_KEY"))

    def call(prompt: str, temperature: float) -> str:
        response = client.chat.completions.create(
            model=OPENROUTER_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            max_tokens=MAX_OUTPUT_TOKENS,
        )
        return response.choices[0].message.content

    return call


def get_llm_client():
    """
    Shared LLM client for all features/ modules (vocabulary_categorizer.py,
    extractor.py). Single provider: OpenRouter, model OPENROUTER_MODEL.

    Requires OPENROUTER_API_KEY in .env — https://openrouter.ai/keys
    """
    if not os.getenv("OPENROUTER_API_KEY"):
        raise RuntimeError("OPENROUTER_API_KEY is not set in .env.")

    print(f"🔌 LLM provider: openrouter (model={OPENROUTER_MODEL})")
    return _ChatClient(_make_openrouter_call())


# --- batch settings for vocabulary_categorizer.py (unchanged) ---

# How many terms per batch. Kept small (not all 2416 at once) because:
# (1) a longer prompt means higher risk of a JSON error, and (2) if a
# batch fails, only that batch is resent, not the whole vocabulary.
VOCAB_BATCH_SIZE = 60

# How many characters of "meaning" to send per term to the LLM — the full
# definition isn't needed (some are quite long), just enough to disambiguate.
VOCAB_MEANING_CHAR_CAP = 180