# Generated by Django 6.0.7 on 2026-07-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="bytes")),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("image", "تصویر")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "آپلود شده"),
                            ("processing", "در حال پردازش"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "ocr_engine",
                    models.CharField(
                        choices=[("gemini", "Gemini Flash"), ("glm", "GLM-OCR")],
                        default="gemini",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سند",
                "verbose_name_plural": "اسناد",
                "ordering": ["-created_at"],
            },
        ),
    ]
